server:
  port: 8888

spring:
  freemarker:
    suffix: .ftl

  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/factory
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

    properties.hibernate.jdbc.lob.non_contextual_creation: true
